services:
  - type: web
    name: feedback-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: MANAGER_CHAT_ID
        sync: false
      - key: DATABASE_URL
        sync: false 